### ISSUE TITLE
Problem from ng-table change

### ISSUE THREAD

**Issue by chen4w** [AschPlatform/asch-frontend#1]
ng-table 1.0.0 made some changes
https://github.com/esvit/ng-table/blob/master/CHANGELOG.md#breaking-changes
It is not backward compatible with the fellowing code:

_getData: function($defer,params) {_

**Comment by sqfasd** [comment]
https://github.com/sqfasd/asch-frontend/commit/bdd4e9ffe6cff59a6a883efa0f202cd9399cc2e5

Fixed by rollback ngTable to 0.5.4
