### ISSUE TITLE
客户端在遇到时间同步问题无法转账时能够自动修复

### ISSUE THREAD

**Issue by sqfasd** [AschPlatform/asch-frontend#14]
实现思路：
需要将asch-js更新到1.3.9版本，使用最新的接口，AschJS.options.set('clientDriftSeconds', 10)，将时间偏移设置为更大，默认的时间调整是5秒，如果出现Invalid transaction timestamp，则将这个参数调大一点，每次建议调大5秒，直到成功为止（如果遇到的不是时间问题，也停止）

**Comment by lbgod2222** [comment]
RequestURL: http://testnet.cctime.org/api/dapps/d352263c517195a8b612260971c7af869edca305bb64b471686323817e57b2c1/transfers?limit=5&offset=0&ownerId=AFnwUuET2XddPtqpFb2ns78CQEqc7KZ6vD&currency=

**Comment by lbgod2222** [comment]
Arguments:
limit:5
offset:0
ownerId:AFnwUuET2XddPtqpFb2ns78CQEqc7KZ6vD
currency:

**Comment by lbgod2222** [comment]
git diff 总是只显示某一个文件的不同，效仿网上的办法导出到一个文件里格式会被打乱，怎么破

**Comment by mike-tian** [comment]
已完成，关闭issue
