### ISSUE TITLE
获取交易记录，limit设置为5，返回数量为7，相似情况曾经发生过

### ISSUE THREAD

**Issue by lbgod2222** [AschPlatform/asch-frontend#16]
如题

**Comment by lbgod2222** [comment]
Arguments:
limit:5
offset:0
ownerId:AFnwUuET2XddPtqpFb2ns78CQEqc7KZ6vD
currency:

**Comment by lbgod2222** [comment]
RequestURL: http://testnet.cctime.org/api/dapps/d352263c517195a8b612260971c7af869edca305bb64b471686323817e57b2c1/transfers?limit=5&offset=0&ownerId=AFnwUuET2XddPtqpFb2ns78CQEqc7KZ6vD&currency=

**Comment by lbgod2222** [comment]
返回内容：
count：15 总数
success:true
transfers：Array(10)  返回十个内容

**Comment by sqfasd** [comment]
Move to cctime
