### ISSUE TITLE
asch-frontend账户二维码生成

### ISSUE THREAD

**Issue by sqfasd** [AschPlatform/asch-frontend#23]
1. 在【个人中心】页面使用secret生成一个二维码，供手机端扫描导入账户
2. 生成的二维码组件默认隐藏，需要用户点击一个【展开】按钮来展示出来，相应的也要提供一个【收起】按钮进行隐藏
3. 协议为：/asch/secret/$encode/$secret

简单解释下协议参数
$encode表示编码方式, 比如hex，base64，raw
$secret是编码后的密码内容

**Comment by sqfasd** [comment]
@kimziv

**Comment by mike-tian** [comment]
已完成，关闭issue
