### ISSUE TITLE
浏览器兼容性处理

### ISSUE THREAD

**Issue by ByCnck** [AschPlatform/asch-frontend#28]
目前asch-frontend只支持最新的chrome浏览器，其他浏览器一般情况下转账或者注册资产时都会报"Server error !" 。建议的2种处理方法：
1、在登录页面直接判断用户浏览器，如果浏览器不是chrome或者低于59.0版本的chrome，直接报错“请使用版本大于59.xxx版本的chrome浏览器访问本站”
2、如果后端有返回"Server error !"，那么直接给用户提示“请使用版本大于59.xxx版本的chrome浏览器访问本站”

**Comment by lbgod2222** [comment]
commit d3b48bae5491adbd2758f01023dc6471b45c1a4e
