### ISSUE TITLE
npm install 的时候一直报错，请问这是什么原因？

### ISSUE THREAD

**Issue by liulinhui** [AschPlatform/asch-frontend#3]
> asch-frontend@1.1.0 build D:\gitRepository\nodejs\asch-frontend
> browserify build.js -o bower_components/bitcore-mnemonic.js && cp node_modules/asch-js/browserify-asch.js bower_components/

Error: Cannot find module '../../../../.1.1.4@is-buffer/index.js' from 'C:\Users\linkage\AppData\Roaming\npm\node_modules\browserify\node_modules\.1.0.2@core-util-is\lib'
    at C:\Users\linkage\AppData\Roaming\npm\node_modules\browserify\node_modules\.1.1.7@resolve\lib\async.js:55:21
    at load (C:\Users\linkage\AppData\Roaming\npm\node_modules\browserify\node_modules\.1.1.7@resolve\lib\async.js:69:43)
    at onex (C:\Users\linkage\AppData\Roaming\npm\node_modules\browserify\node_modules\.1.1.7@resolve\lib\async.js:92:31)
    at C:\Users\linkage\AppData\Roaming\npm\node_modules\browserify\node_modules\.1.1.7@resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

**Comment by ByCnck** [comment]
换linux，目前开发都是基于linux的，windows会在之后适配。
