### ISSUE TITLE
Make all strings in the GUI multilingual

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch-frontend#31]
I have noticed that not all strings in the GUI are multilangual. 
I will revise this.

Kind regards
a1300

**Comment by lbgod2222** [comment]
@a1300 Got it,  but we still hope to fix all bad features after our asch-core refactoring,  and yes, a whole new website wallet with new frame kit is inevitable when the time comes.

**Comment by a1300** [comment]
@lbgod2222 good to know :-) 
Does it pay off to put in all the work to refactor the "old" wallet? When is the development of the new wallet planned?
Kind regards
a1300

**Comment by lbgod2222** [comment]
@a1300 Forgive me for my poor expresssion, i mean, our team was planning to refactor our "core code", and the web wallet is just a dapp based on it, so our Font-end gonna rebuild a wallet after our "core code" refactoring done, and we all glad for your contribution ：)
